### PR TITLE
feat: remove user stories from url-shortener

### PR DESCRIPTION
**Pull request by Sky020**
Related to Issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/39721

As is, easy-peasy-lemon-squeezy.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@Sky020 Internally, we discussed deleting all the README.md files from the projects after all the `learn` files have been updated and boilerplate repos have been updated.  However, I will leave this PR open for now in case we decided to keep this basic link in the projects' README.md files.

The `Has user stories remove `checkbox under the `Demo Project` table column of https://github.com/freeCodeCamp/freeCodeCamp/issues/39721 was more to do with removing the user stories from the landing pages, but if we did decide to keep the README.md files, then this PR removes them from this project.

**Comment by Sky020** [comment]
@RandellDawson That makes sense, Thinking it through, there should be no reason anyone ends up on this README file.

Well, in that case, this project just so happens to not include any user stories in the landing page. So, the box can be ticked. Sorry about this.

**Review by RandellDawson — APPROVED** [review]
LGTM

**Comment by RandellDawson** [comment]
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
