### PR TITLE
fix: message board demo project to pass with new tests

### PR DESCRIPTION
**Pull request by moT01**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

This fixes up this project so all the functional tests pass, and the correct replies are given to align with the user stories on /learn. Which will also make it pass the new tests on https://github.com/freeCodeCamp/freeCodeCamp/pull/43041

### CODE REVIEW

**Comment by ieahleen** [comment]
Blocked until https://github.com/freeCodeCamp/freeCodeCamp/pull/43041 is merged

**Comment by ShaunSHamilton** [comment]
@moT01 I just updated this to match the slight change in tests/user-stories from the linked PR.

---

Side note: We should probably set up proper linting on this repo so we do not constantly get the changes of formatting.

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍

**Review by nhcarrigan — APPROVED** [review]
Passes the tests!

**Comment by moT01** [comment]
Did the .rocks server get updated with this @nhcarrigan @ShaunSHamilton ?

**Comment by ShaunSHamilton** [comment]
@moT01 I did not update it - completely slipped my mind that this was not a boilerplate. I will catch this up in Chat.

**Pull request merged**
