### PR TITLE
chore: use workspaces

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
We had rolled our own workspaces, but I think we can use npm workspaces and cut down on duplication. Also, hopefully this plays better with renovate.

Also, I tested this locally using node 16 and all was well, so I think we should move to using that if possible.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@nhcarrigan what do you reckon to this approach? It seems okay (tests passing and so on), but I don't know if there are some gotchas I've missed.

**Comment by ojeytonwilliams** [comment]
Yeah, I'm leaning towards updating both node and npm if we can.  I think it's better to fix migration issues now than be totally confused by them when we *have* to migrate.  Particularly given that there don't seem to be any!

> Whichever we decide, we should probably update the engines fields in all of these to match - currently npm ci is very noisy.

For sure.  I can do that in this PR.

**Comment by ojeytonwilliams** [comment]
> Particularly given that there don't seem to be any!
 
 Or I just missed all of them :man_facepalming:

**Comment by nhcarrigan** [comment]
Could be a flake, tbh. Database stuff can get wonky sometimes.

We'll likely end up needing to remove node 12, I'd imagine - it's 3 months away from end of life, and some of these package updates probably won't support it. Cross that bridge when we get to it, I think.

**Review by nhcarrigan — APPROVED** [review]
Anyway I think we can get this in as is and start looking at these deps.

**Comment by ojeytonwilliams** [comment]
Cheers @nhcarrigan let's see what renovate makes of this...

I left the tests running on multiple versions of node for now, but we might need to change that.  At the very least by dropping node 12 support, as you mentioned.

**Pull request merged**
