### PR TITLE
feat: configure formatting tools

### LINKED ISSUE #497: Configure Prettier, ESLint and Formatting Tools
**Looking forward for reporting a security issue:**
Please report security issues by following our security policy: `https://contribute.freecodecamp.org/#/security`

**Describe the bug**
Whenever I hit the "Format with Prettier" shortcut in Visual Studio Code; it seems like the entire file is set as changed rather than just the new lines of code. 

**To Reproduce**
1. Open up the repository in Visual Studio Code 
2. Click on the american-british-translator app folder
3. Open the server file
4. Format the document with Prettier 
5. See error

**Expected behavior**
Only the lines I added should have been modified via Prettier. 

**Screenshots**
Screenshot from GitHub Desktop

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: FireFox
 - Version: 119.0

**Additional context**
I would rather not add the endpoint for this app *before* this issue is resolved.

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #497

This adds a husky pre-commit hook and automatically lints all committed files with lint-staged.

### CODE REVIEW

**Review by raisedadead — APPROVED** [review]

**Comment by raisedadead** [comment]
I believe, we need to run prettier on all the files at least once before we merge this. No?

**Comment by naomi-lgbt** [comment]
> I believe, we need to run prettier on all the files at least once before we merge this. No?

Not necessarily. We could do that in a follow-up PR if we wanted.

**Comment by a2937** [comment]
> I believe, we need to run prettier on all the files at least once before we merge this. No? Also @a2937 are you on our discord chat by any chance?

Yes I am in the discord chat. And I can try running it for sure.

**Comment by a2937** [comment]
Because there are literally 210 files that get reformatted, even after I create a `.prettierignore` file, running `prettier` on the project should be held off until it can be done in a followup PR.

**Pull request merged**
