### PR TITLE
fix: sanitise html

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

Catches a vulnerability reported on our Discord by @Tezcatlipoca0000.

I can't get the app to work locally but this *should* resolve the issue. @raisedadead you should see a copy of the report in our inbox too.

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
Note that if we are happy with this fix, we'll want to update the boilerplate to include this package - and likely update the challenge instructions to indicate how to use it.

**Comment by Tezcatlipoca0000** [comment]
Mmmmm I'm very ignorant on the subject but.
sanitize-html does allow, for instance, the b tag.
And... For an XSS attack the <script> tag is not necessary.
For example this could still happen:
<b onmouseover=alert(‘XSS testing!‘)>

**Comment by raisedadead** [comment]
IMHO - we can rule out the vulnerability (which exists) as low-risk and move on. Adding this fix and the package adds additional noise to what the projects are about and is a distraction.

We should cover infosec and topics like XSS etc., in some other part of the curriculum and reference it in a non-intrusive manner.

**Comment by raisedadead** [comment]
For clarity,

The vulnerability is low-risk because it is being used on a "demo" app and users should not be entering real-world or sensitive info. 

Again explaining that is also beyond the scope of the project, but a quick warning across all such forms which we host is something that I am willing to do.

Something like:

Warning: This is a demo academic project. Do not share any sensitive information like your real emails, passwords, etc. here.

**Comment by Sboonny** [comment]
Can we delete the data periodically? Like how we do so in freecodecamp 🤔.

The issue will still exist for future projects, and we won't need to worry about this carrying data.

**Comment by ShaunSHamilton** [comment]
> I can't get the app to work locally but this should resolve the issue.

I tested this on Gitpod - it is setup for a single click, and everything JUST WORKS 🤩

**Comment by naomi-lgbt** [comment]
I consistently forget that GitPod exists lol

**Comment by ShaunSHamilton** [comment]
We spoke about this during the dev meeting.

Whilst the scope of this issue is small, it has, in the past, caused the client to be unusable - which defeats the whole purpose of having a demo-app.

Seeing as these changes only affect server-side, Campers **should** never see it, then wonder why they were never taught it.

_At first, I thought there would be a way to make this work such that it did not require a public, persistent DB, but see now that is not possible (due to tests)_

**Comment by ShaunSHamilton** [comment]
I do not know what to do about that Socket report?

I did not dig into each dep, but `sanitize-html` does not _directly_ depend on either of those packages mentioned.

**Comment by raisedadead** [comment]
> I do not know what to do about that Socket report?

They must be a part of some other dependency we use in the project. If you are quite sure that the report is false-positive or a low risk, we can proceed with merging, regardless.

**Review by ShaunSHamilton — APPROVED** [review]
This LGTM 👍 

---

I investigated Socket's complaints. The issue is it is comparing the names we gave our apps `package.json > { "name": "stocks" }` with published NPM packages.

I would hope there is a way to silence that.

**Comment by raisedadead** [comment]
> I would hope there is a way to silence that.

We could just rename the packages something along these lines `@freecodecamp/demo-stocks` and mark the package private as well. But that's for another day.

**Comment by raisedadead** [comment]
Anyone willing to deploy this?

**Comment by ShaunSHamilton** [comment]
> Anyone willing to deploy this?

I could give it a _bash_ 😁

**Pull request merged**
