### PR TITLE
fix: remove metric-imp user stories

### PR DESCRIPTION
**Pull request by moT01**
Related to: https://github.com/freeCodeCamp/freeCodeCamp/issues/39721

Wait until we have added user stories to learn to merge this.

### CODE REVIEW

**Comment by Sky020** [comment]
Also this:  https://github.com/freeCodeCamp/demo-projects/blob/b4e53fb4a3970654379de55c55663e7dfc93cde8/metric-imperial-converter/views/index.html#L4

I would suggest that be changed, as well as `line 15` to be _"Metric/Imperial Converter"_

**Comment by moT01** [comment]
Yea, I was wondering what would be fine to just add on to these PR's - there's other things I would like to change as well. Not sure if we should just tack them on or keep them separate.

**Review by RandellDawson — APPROVED** [review]
We can merge this one too now.

**Comment by RandellDawson** [comment]
@Sky020 We can tackle cleaning the html up in a separate PR.

**Pull request merged**
