### PR TITLE
fix(javascript-calculator): adjust minus unicode, add noreferrer

### PR DESCRIPTION
**Pull request by Dave2188**
Checklist:

- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Partially addresses [#49045](https://github.com/freeCodeCamp/freeCodeCamp/issues/49045)

I included the closing number for issue 49045 because while working on it, I could not replicate that specific issue. In the process, I discovered that the minus operator was showing as a zero.  I changed the character based on the warning and has seemed to fix the issue. 

Also was receiving a warning due to missing rel-tag, so I included that as well.  

Screenshot 2023-02-14 at 12 00 08 AM

Screenshot 2023-02-14 at 7 35 20 PM

Screenshot 2023-02-14 at 7 31 32 PM

### CODE REVIEW

**Review by ShaunSHamilton — APPROVED** [review]
Thank you for taking the time to contribute.

I am happy with this change. I also see the warning about the uncommon unicode character. However, I do not see a `0` in place of it on the production app.

How/where did you get the `301 = 2`?

**Comment by Dave2188** [comment]
Every time I would hit the minus key a zero would appear on the calculator. The functionality was working correctly. The only thing I could think of was that it was having trouble with the character. I'm on a mac with chrome if that could be playing a part.

**Review by scissorsneedfoodtoo — APPROVED** [review]
Thank you for taking the time to investigate this issue and for these fixes, @Dave2188.

I can replicate this on my Mac running Chrome, where 9-3=6 appears as 903=6:

image

Firefox doesn't have the same issue, and the - operator is displayed correctly.

The fixes here seem to do the trick. Here are some screenshots from Chrome on my Mac after the fixes:

image

image

image

**Comment by Dave2188** [comment]
I found the fix to the last issue discussed above and another around when you minus a number by a negative number. Should push it to this branch or create a new one for checking?

**Comment by Dave2188** [comment]
@scissorsneedfoodtoo  These are some shots of the output after entering  +0+0+0+0+0+0+0+-1, which now displays correctly, and 9 - -9 before displayed 18 and now displays correctly with 0. 

Screenshot 2023-02-15 at 10 49 59 PM
Screenshot 2023-02-15 at 11 21 23 PM
Screenshot 2023-02-16 at 7 13 06 PM

**Review by ShaunSHamilton — APPROVED** [review]
Thank you for all your work on this 👍

**Review by naomi-lgbt — APPROVED** [review]

**Comment by naomi-lgbt** [comment]
Changes deployed!

**Pull request merged**
